Repository DeveloperAcademy-POSTECH/MC3-Team16-SoonDoongBoo, pull requests merged in 2022-07, with the labels that each got.

#9 [Feature] PickerView, Alert
  Dear/Dear.xcodeproj/project.pbxproj
  Dear/Dear/AppDelegate.swift
  Dear/Dear/Base.lproj/Main.storyboard
  Dear/Dear/Controller/HospitalViewController.swift
  Dear/Dear/Controller/LetterViewController.swift
  Dear/Dear/Controller/ThirdViewController.swift
  Dear/Dear/Controller/ViewController.swift
  Dear/Dear/Model/Data.swift
  Dear/Dear/Model/GoogleService-Info.plist
  Dear/Dear/Second.storyboard
  Dear/Dear/UIViewController+Extension.swift
  Dear/Dear/View/Base.lproj/LaunchScreen.storyboard
  Dear/Dear/View/Base.lproj/Main.storyboard
  Dear/Dear/View/Third.storyboard
Labels: enhancement, help wanted

#47 Feat/firebase
  Dear/Dear/Services/FirebaseService.swift
Labels: enhancement

#53 [FEAT] 사용자 선택, 병원 선택 뷰 연결
  Dear/Dear/Controllers/HospitalViewController.swift
  Dear/Dear/Controllers/SelectUserViewController.swift
  Dear/Dear/SceneDelegate.swift
  Dear/Dear/Views/SelectHospital.storyboard
  Dear/Dear/Views/SelectUser.storyboard
Labels: enhancement

#54 [Feature] 간호사 메인 뷰 기능 구현
  Dear/Dear.xcodeproj/project.pbxproj
  Dear/Dear/Assets.xcassets/Mood/temp_pink01.colorset/Contents.json
  Dear/Dear/Cell/DDayCustomTableViewCell.swift
  Dear/Dear/Cell/LetterCustomTableViewCell.swift
  Dear/Dear/Cell/MoodText.swift
  Dear/Dear/Cell/NurseMainSectionHeader.swift
  Dear/Dear/Cell/NurseMainTableHeader.swift
  Dear/Dear/Cell/SelectMood.swift
  Dear/Dear/Controllers/NurseMainController.swift
  Dear/Dear/CornerRadius+Extensions.swift
  Dear/Dear/Date+Extension.swift
  Dear/Dear/ViewController.swift
  Dear/Dear/Views/NurseMain.storyboard
  Dear/Dear/Views/SelectMood.xib
  Dear/Dear/XibUIViewExtension.swift
Labels: enhancement

#57 [Feature] 간호사 처방전 뷰 UI
  Dear/Dear.xcodeproj/project.pbxproj
  Dear/Dear/Controllers/NursePrescriptionViewController.swift
  Dear/Dear/Views/NursePrescriptionView.storyboard
Labels: enhancement

#56 [FEAT] 병원 선택 뷰에서 파이어베이스 연결 및 병원 이름 UserDefaults 저장
  Dear/Dear/Controllers/HospitalViewController.swift
  Dear/Dear/Views/SelectHospital.storyboard
Labels: enhancement

#63 [FEAT] 각 화면 연결 및 메인 화면 분기 구현
  Dear/Dear/Controllers/HospitalViewController.swift
  Dear/Dear/SceneDelegate.swift
  Dear/Dear/Views/NurseMain.storyboard
  Dear/Dear/Views/NursePillBagView.storyboard
Labels: enhancement

#67 [BUGFIX] gRPC 패키지 업데이트
  Dear/Dear.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: bug

#71 [Feature] 간호사 메인 뷰 - 차트 구현
  Dear/Dear/Assets.xcassets/ColorExtension/coral.colorset/Contents.json
  Dear/Dear/Controllers/NurseMainController.swift
  Dear/Dear/Date+Extension.swift
  Dear/Dear/Views/NurseMain.storyboard
Labels: enhancement

#77 [Feature] 처방전 뷰 수정
  Dear/Dear.xcodeproj/project.pbxproj
  Dear/Dear/Controllers/LetterViewController.swift
  Dear/Dear/Date+Extension.swift
  Dear/Dear/UIViewController+Extension.swift
  Dear/Dear/Views/NursePrescriptionView.storyboard
  Dear/Dear/Views/WriteLetter.storyboard
Labels: enhancement

#78 [BUGFIX/FEAT] 실행 시 rootViewContorller 변경 및 뷰 연결
  Dear/Dear/Controllers/HospitalViewController.swift
  Dear/Dear/Controllers/LetterViewController.swift
  Dear/Dear/Controllers/NurseMainController.swift
  Dear/Dear/Controllers/NursePillBagViewController.swift
  Dear/Dear/Controllers/PatientPillBagViewController.swift
  Dear/Dear/SceneDelegate.swift
  Dear/Dear/Services/FirebaseService.swift
  Dear/Dear/Views/PatientPillBagView.storyboard
  Dear/Dear/Views/WriteLetter.storyboard
Labels: bug, enhancement
